[DbAssignmentAddApp | ERROR] No assignment id provided.
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID '{assignment_id}': {'duedate': None}
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[DbAssignmentAddApp | ERROR] Exception while loading config file /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py", line 4, in <module>
        c.Exchange.course_id = course_id
    NameError: name 'course_id' is not defined
[DbAssignmentAddApp | ERROR] Exception while loading config file /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py", line 4, in <module>
        c.Exchange.course_id = course_id
    NameError: name 'course_id' is not defined
[DbAssignmentApp | ERROR] Exception while loading config file /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py", line 4, in <module>
        c.Exchange.course_id = course_id
    NameError: name 'course_id' is not defined
[DbApp | ERROR] Exception while loading config file /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py", line 4, in <module>
        c.Exchange.course_id = course_id
    NameError: name 'course_id' is not defined
[NbGraderApp | ERROR] Exception while loading config file /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/ipython_genutils/py3compat.py", line 288, in execfile
        builtin_mod.execfile(filename, *where)
      File "/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/nbgrader_config.py", line 4, in <module>
        c.Exchange.course_id = course_id
    NameError: name 'course_id' is not defined
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[AutogradeApp | ERROR] An assignment id must be specified, either as an argument or with --assignment
[AutogradeApp | ERROR] No notebooks were matched by '/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/*/tentamen'
[AutogradeApp | ERROR] No notebooks were matched by '/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/*/tentamen'
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=06d9d2f908ac6585266aeb9f2ce7a6553d1da4daf252eeff
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=06d9d2f908ac6585266aeb9f2ce7a6553d1da4daf252eeff
[NotebookApp | WARNING] 404 GET /api/kernels/2d1fd1b6-e9a9-44a5-b89e-7f30a6d75694/channels?session_id=4852A384D7144A4DACA037296AAA23B3 (::1): Kernel does not exist: 2d1fd1b6-e9a9-44a5-b89e-7f30a6d75694
[NotebookApp | WARNING] 404 GET /api/kernels/2d1fd1b6-e9a9-44a5-b89e-7f30a6d75694/channels?session_id=4852A384D7144A4DACA037296AAA23B3 (::1) 176.50ms referer=None
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | WARNING] Replacing stale connection: 2d1fd1b6-e9a9-44a5-b89e-7f30a6d75694:4852A384D7144A4DACA037296AAA23B3
[NotebookApp | WARNING] 404 GET /api/kernels/0c8389bf-3673-49cc-b1b1-d9f3b30af5d3/channels?session_id=F909D5A4E61543DFB9E519A13077C322 (::1): Kernel does not exist: 0c8389bf-3673-49cc-b1b1-d9f3b30af5d3
[NotebookApp | WARNING] 404 GET /api/kernels/0c8389bf-3673-49cc-b1b1-d9f3b30af5d3/channels?session_id=F909D5A4E61543DFB9E519A13077C322 (::1) 8.48ms referer=None
[NotebookApp | INFO] Kernel started: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | INFO] Kernel started: 7b9155eb-54b4-4276-b5cc-1d9ab4b5087f
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 7b9155eb-54b4-4276-b5cc-1d9ab4b5087f
[AssignApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/source/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Writing 980 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Setting destination file permissions to 644
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | CRITICAL] You don't own the directory: /srv/nbgrader/exchange/netwerkanalyse
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[AssignApp | ERROR] No notebooks were matched by '/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/source/./{assignment_id}'
[AutogradeApp | ERROR] No notebooks were matched by '/Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/*/tentamen'
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[AssignApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/source/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Writing 980 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Setting destination file permissions to 644
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Kernel interrupted: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | INFO] Kernel interrupted: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | INFO] Kernel interrupted: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[AutogradeApp | ERROR] No student with ID '10735291' exists in the database
[AutogradeApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/autograde.py", line 82, in init_assignment
        raise NbGraderException(msg)
    NbGraderException: No student with ID '10735291' exists in the database
    
[AutogradeApp | ERROR] There was an error processing assignment 'tentamen' for student '10735291'
[AutogradeApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[AutogradeApp | ERROR] No student with ID '10735291' exists in the database
[AutogradeApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/autograde.py", line 82, in init_assignment
        raise NbGraderException(msg)
    NbGraderException: No student with ID '10735291' exists in the database
    
[AutogradeApp | ERROR] There was an error processing assignment 'tentamen' for student '10735291'
[AutogradeApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[AutogradeApp | INFO] Creating/updating student with ID '10735291': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | WARNING] Skipping unknown notebook: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen_10735291.ipynb
[AutogradeApp | ERROR] No notebooks found, did you forget to run 'nbgrader assign'?
[AutogradeApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/autograde.py", line 140, in init_assignment
        raise NbGraderException(msg)
    NbGraderException: No notebooks found, did you forget to run 'nbgrader assign'?
    
[AutogradeApp | ERROR] There was an error processing assignment 'tentamen' for student '10735291'
[AutogradeApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AutogradeApp | INFO] Creating/updating student with ID '10735291': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | WARNING] Skipping unknown notebook: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen_10735291.ipynb
[AutogradeApp | ERROR] No notebooks found, did you forget to run 'nbgrader assign'?
[AutogradeApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/autograde.py", line 140, in init_assignment
        raise NbGraderException(msg)
    NbGraderException: No notebooks found, did you forget to run 'nbgrader assign'?
    
[AutogradeApp | ERROR] There was an error processing assignment 'tentamen' for student '10735291'
[AutogradeApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[AutogradeApp | INFO] Creating/updating student with ID '10735291': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Sanitizing /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Writing 980 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Autograding /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Executing notebook with kernel: python3
[AutogradeApp | INFO] Writing 977 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Setting destination file permissions to 444
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AutogradeApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] 301 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8 (::1) 18.65ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | WARNING] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 (::1) 10.01ms referer=http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] 302 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/next (::1) 20.26ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] 302 GET /tree (::1) 8.74ms
[NotebookApp | WARNING] 404 GET /apple-touch-icon-precomposed.png (::1) 3.46ms referer=None
[NotebookApp | WARNING] 404 GET /apple-touch-icon.png (::1) 2.17ms referer=None
[NotebookApp | INFO] 302 GET /tree (::1) 1.43ms
[NotebookApp | WARNING] 404 GET /apple-touch-icon-precomposed.png (::1) 3.36ms referer=None
[NotebookApp | WARNING] 404 GET /apple-touch-icon.png (::1) 7.11ms referer=None
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] 301 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8 (::1) 24.47ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | WARNING] 404 GET /apple-touch-icon-precomposed.png (::1) 4.44ms referer=None
[NotebookApp | WARNING] 404 GET /apple-touch-icon.png (::1) 2.60ms referer=None
[NotebookApp | WARNING] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 (::1) 6.12ms referer=http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/
[NotebookApp | ERROR] Uncaught exception PUT /formgrader/api/comment/24b2c485c86f4e22b56f44232df4a810 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='PUT', uri='/formgrader/api/comment/24b2c485c86f4e22b56f44232df4a810', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'X-Csrftoken': '2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'Content-Length': '210', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1', 'Cookie': 'username-localhost-8888="2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/apihandlers.py", line 83, in put
        self.gradebook.db.commit()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
        self._prepare_impl()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
        self.session.flush()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
        self._flush(objects)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
        transaction.rollback(_capture_exception=True)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
        flush_context.execute()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
        rec.execute(self)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
        uow
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
        mapper, table, update)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
        execute(statement, multiparams)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
        return meth(self, multiparams, params)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
        context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
        exc_info
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
        context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
        cursor.execute(statement, parameters)
    OperationalError: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE comment SET manual_comment=? WHERE comment.id = ?'] [parameters: (u'Beetje karig antwoord', u'24b2c485c86f4e22b56f44232df4a810')]
[NotebookApp | ERROR] {
      "Origin": "http://localhost:8888", 
      "X-Csrftoken": "2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "Content-Length": "210", 
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a\"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "Content-Type": "application/json"
    }
[NotebookApp | ERROR] 500 PUT /formgrader/api/comment/24b2c485c86f4e22b56f44232df4a810 (::1) 39.50ms referer=http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1
[NotebookApp | ERROR] Uncaught exception GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/next (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/next', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'Cookie': 'username-localhost-8888="2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'Referer': 'http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 188, in get
        submission = self.gradebook.find_submission_notebook_by_id(submission_id)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/api.py", line 2003, in find_submission_notebook_by_id
        .filter(SubmittedNotebook.id == notebook_id)\
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in one
        ret = self.one_or_none()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
        ret = list(self)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE comment SET manual_comment=? WHERE comment.id = ?'] [parameters: (u'Beetje karig antwoord', u'24b2c485c86f4e22b56f44232df4a810')]
[NotebookApp | ERROR] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6", 
      "Connection": "keep-alive", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a\"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "Referer": "http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1", 
      "Upgrade-Insecure-Requests": "1"
    }
[NotebookApp | ERROR] 500 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/next (::1) 10.39ms referer=http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1
[NotebookApp | ERROR] Uncaught exception GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/prev (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/prev', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'Cookie': 'username-localhost-8888="2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'Referer': 'http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 188, in get
        submission = self.gradebook.find_submission_notebook_by_id(submission_id)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/api.py", line 2003, in find_submission_notebook_by_id
        .filter(SubmittedNotebook.id == notebook_id)\
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in one
        ret = self.one_or_none()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
        ret = list(self)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE comment SET manual_comment=? WHERE comment.id = ?'] [parameters: (u'Beetje karig antwoord', u'24b2c485c86f4e22b56f44232df4a810')]
[NotebookApp | ERROR] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6", 
      "Connection": "keep-alive", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a\"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "Referer": "http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1", 
      "Upgrade-Insecure-Requests": "1"
    }
[NotebookApp | ERROR] 500 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/prev (::1) 4.64ms referer=http://localhost:8888/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/?index=1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | ERROR] Uncaught exception GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/ (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Cookie': 'username-localhost-8888="2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'If-None-Match': '"209750314b6f058899e5b208ad9852d9201a7a70"', 'Referer': 'http://localhost:8888/formgrader/gradebook/tentamen/Tentamen', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6'})
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 77, in get
        submission = self.gradebook.find_submission_notebook_by_id(submission_id)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/api.py", line 2003, in find_submission_notebook_by_id
        .filter(SubmittedNotebook.id == notebook_id)\
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in one
        ret = self.one_or_none()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
        ret = list(self)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE comment SET manual_comment=? WHERE comment.id = ?'] [parameters: (u'Beetje karig antwoord', u'24b2c485c86f4e22b56f44232df4a810')]
[NotebookApp | ERROR] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
      "Upgrade-Insecure-Requests": "1", 
      "Connection": "keep-alive", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a\"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "If-None-Match": "\"209750314b6f058899e5b208ad9852d9201a7a70\"", 
      "Referer": "http://localhost:8888/formgrader/gradebook/tentamen/Tentamen", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
    }
[NotebookApp | ERROR] 500 GET /formgrader/submissions/b1ffe40da9bb40edb0e02e079ed216c8/ (::1) 3.20ms referer=http://localhost:8888/formgrader/gradebook/tentamen/Tentamen
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[AssignApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/tentamen
[AutogradeApp | INFO] Skipping existing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[AutogradeApp | INFO] Creating/updating student with ID '10735291': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | WARNING] Skipping unknown notebook: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | ERROR] No notebooks found, did you forget to run 'nbgrader assign'?
[AutogradeApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/autograde.py", line 140, in init_assignment
        raise NbGraderException(msg)
    NbGraderException: No notebooks found, did you forget to run 'nbgrader assign'?
    
[AutogradeApp | ERROR] There was an error processing assignment 'tentamen' for student '10735291'
[AutogradeApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[AssignApp | INFO] Updating/creating assignment 'tentamen': {}
[AssignApp | ERROR] Cannot modify existing assignment 'Assignment<tentamen>' because there are submissions associated with it
[AssignApp | ERROR] There was an error processing assignment: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/source/./tentamen
[AssignApp | ERROR] Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/base.py", line 289, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/assign.py", line 140, in init_assignment
        self._clean_old_notebooks(assignment_id, student_id)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/converters/assign.py", line 102, in _clean_old_notebooks
        raise NbGraderException(msg)
    NbGraderException: Cannot modify existing assignment 'Assignment<tentamen>' because there are submissions associated with it
    
[AssignApp | ERROR] There was an error processing assignment 'tentamen' for student '.'
[AssignApp | ERROR] Please see the error log (.nbgrader.log) for details on the specific errors on the above failures.
[DbAssignmentAddApp | INFO] Creating/updating assignment with ID 'tentamen': {'duedate': None}
[AssignApp | INFO] Updating/creating assignment 'tentamen': {}
[AssignApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/source/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Writing 980 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/release/./tentamen/Tentamen.ipynb
[AssignApp | INFO] Setting destination file permissions to 644
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[AutogradeApp | INFO] Creating/updating student with ID '10735291': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Sanitizing /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/submitted/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Writing 980 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Autograding /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Converting notebook /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[AutogradeApp | INFO] Writing 977 bytes to /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/autograded/10735291/tentamen/Tentamen.ipynb
[AutogradeApp | INFO] Setting destination file permissions to 444
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | ERROR] Uncaught exception GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'Cookie': 'username-localhost-8888="2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559', 'Referer': 'http://localhost:8888/formgrader/gradebook/tentamen/Tentamen', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 77, in get
        submission = self.gradebook.find_submission_notebook_by_id(submission_id)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/nbgrader/api.py", line 2003, in find_submission_notebook_by_id
        .filter(SubmittedNotebook.id == notebook_id)\
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2749, in one
        ret = self.one_or_none()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2719, in one_or_none
        ret = list(self)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2790, in __iter__
        return self._execute_and_instances(context)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2811, in _execute_and_instances
        close_with_result=True)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2820, in _get_bind_args
        **kw
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in _connection_from_session
        conn = self.session.connection(**kw)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 966, in connection
        execution_options=execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 971, in _connection_for_bind
        engine, execution_options)
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
        self._assert_active()
      File "/Users/Jesse/anaconda/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) attempt to write a readonly database [SQL: u'UPDATE comment SET manual_comment=? WHERE comment.id = ?'] [parameters: (u'Beetje karig antwoord', u'24b2c485c86f4e22b56f44232df4a810')]
[NotebookApp | ERROR] {
      "Accept-Language": "en-us", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6", 
      "Connection": "keep-alive", 
      "Cookie": "username-localhost-8888=\"2|1:0|10:1522683328|23:username-localhost-8888|44:OTNhYjVhMzUxZTgxNDM1Y2JlZjNjMWE0NWIyMmIxNDI=|f37d73527ca37e260a869ec25bdcb54a0995d9684604b4294e5049ef44a6e21a\"; _xsrf=2|0108d136|aabde6d4b12c879c0755cd9dda8b895f|1520326559", 
      "Referer": "http://localhost:8888/formgrader/gradebook/tentamen/Tentamen", 
      "Upgrade-Insecure-Requests": "1"
    }
[NotebookApp | ERROR] 500 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f (::1) 4.02ms referer=http://localhost:8888/formgrader/gradebook/tentamen/Tentamen
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 2 kernels
[NotebookApp | INFO] Kernel shutdown: 7b9155eb-54b4-4276-b5cc-1d9ab4b5087f
[NotebookApp | INFO] Kernel shutdown: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=511c03d8ed432c1cc71a53a7aabb45dff190db86b07da407
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=511c03d8ed432c1cc71a53a7aabb45dff190db86b07da407
[NotebookApp | WARNING] 404 GET /api/kernels/7b9155eb-54b4-4276-b5cc-1d9ab4b5087f/channels?session_id=50F3CAA3B0EB4DB6803A7F08ED781079 (::1): Kernel does not exist: 7b9155eb-54b4-4276-b5cc-1d9ab4b5087f
[NotebookApp | WARNING] 404 GET /api/kernels/7b9155eb-54b4-4276-b5cc-1d9ab4b5087f/channels?session_id=50F3CAA3B0EB4DB6803A7F08ED781079 (::1) 162.78ms referer=None
[NotebookApp | WARNING] 404 GET /api/kernels/46d6dec8-6b54-455b-9cd2-89269bd039c8/channels?session_id=E2EA29F1D4A34CF698C4C4467039E315 (::1): Kernel does not exist: 46d6dec8-6b54-455b-9cd2-89269bd039c8
[NotebookApp | WARNING] 404 GET /api/kernels/46d6dec8-6b54-455b-9cd2-89269bd039c8/channels?session_id=E2EA29F1D4A34CF698C4C4467039E315 (::1) 15.65ms referer=None
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | INFO] 301 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f (::1) 78.83ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | WARNING] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 (::1) 8.04ms referer=http://localhost:8888/formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f/
[NotebookApp | WARNING] Replacing stale connection: 7b9155eb-54b4-4276-b5cc-1d9ab4b5087f:50F3CAA3B0EB4DB6803A7F08ED781079
[NotebookApp | WARNING] Replacing stale connection: 46d6dec8-6b54-455b-9cd2-89269bd039c8:E2EA29F1D4A34CF698C4C4467039E315
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] 302 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f/next (::1) 14.51ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Kernel started: 5cef75d1-cfe8-4bfa-ba02-413ac7942b74
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 5cef75d1-cfe8-4bfa-ba02-413ac7942b74
[NotebookApp | INFO] 301 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f (::1) 9.11ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | WARNING] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 (::1) 3.34ms referer=http://localhost:8888/formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f/
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | INFO] Saving file at /nbgrader workflow.ipynb
[NotebookApp | WARNING] 404 GET /static/components/proptypes/index.js.map (::1) 67.87ms referer=http://localhost:8888/notebooks/nbgrader%20workflow.ipynb
[NotebookApp | WARNING] 404 GET /static/components/preact/preact.min.js.map (::1) 40.85ms referer=http://localhost:8888/notebooks/nbgrader%20workflow.ipynb
[NotebookApp | WARNING] 404 GET /static/components/preact-compat/preact-compat.min.js.map (::1) 9.70ms referer=http://localhost:8888/notebooks/nbgrader%20workflow.ipynb
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: f67d461f-b26b-49d7-9444-5b7914071b86
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel f67d461f-b26b-49d7-9444-5b7914071b86
[NotebookApp | INFO] Saving file at /Untitled.ipynb
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=f605d9e722939e7129c7020b79b6cc766aad7f7ea543537b
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f605d9e722939e7129c7020b79b6cc766aad7f7ea543537b
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Submitted assignments:
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1
[NotebookApp | INFO] Submitted assignments:
[NotebookApp | INFO] Source: /srv/nbgrader/exchange/netwerkanalyse/outbound/ps1
[NotebookApp | INFO] Destination: /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/ps1
[NotebookApp | INFO] Fetched as: netwerkanalyse ps1
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Submitted assignments:
[NotebookApp | INFO] 302 GET /tree/ps1/problem1.ipynb (127.0.0.1) 2.13ms
[NotebookApp | WARNING] Notebook ps1/problem1.ipynb is not trusted
[NotebookApp | INFO] 302 GET /notebooks/ps1/jupyter.png (127.0.0.1) 1.84ms
[NotebookApp | INFO] Kernel started: 071e435d-e689-4bc3-9af7-4ad67161f465
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 071e435d-e689-4bc3-9af7-4ad67161f465
[NotebookApp | INFO] Starting buffering for 071e435d-e689-4bc3-9af7-4ad67161f465:7C56D28F4F01457E8061F7D12812B4C6
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | WARNING] delete /ps1
[NotebookApp | WARNING] 400 DELETE /api/contents/ps1 (127.0.0.1): Directory /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/ps1 not empty
[NotebookApp | WARNING] Directory /Users/Jesse/Dropbox/Notebook-exams/notebook-exams/Scripts/nbgrader/ps1 not empty
[NotebookApp | WARNING] 400 DELETE /api/contents/ps1 (127.0.0.1) 39.49ms referer=http://localhost:8888/tree?
[NotebookApp | INFO] Kernel started: bab4fcc3-f44b-4f92-baf7-9349d169349c
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel bab4fcc3-f44b-4f92-baf7-9349d169349c
[NotebookApp | INFO] Starting buffering for bab4fcc3-f44b-4f92-baf7-9349d169349c:3B3BF7F9604245BE80A550A31067D2F9
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | CRITICAL] You don't own the directory: /srv/nbgrader/exchange/netwerkanalyse
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] 301 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f (127.0.0.1) 14.28ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | WARNING] 404 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 (127.0.0.1) 37.84ms referer=http://localhost:8888/formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f/
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] 302 GET /formgrader/submissions/e59c76afc1c44cfba5e91f4d9d4eb32f/next (127.0.0.1) 13.63ms
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Released assignments:
[NotebookApp | INFO] netwerkanalyse ps1 (already downloaded)
[NotebookApp | INFO] Kernel started: 682f3909-c755-4f9c-8fc5-c966da25172a
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 682f3909-c755-4f9c-8fc5-c966da25172a
[NotebookApp | INFO] Starting buffering for 682f3909-c755-4f9c-8fc5-c966da25172a:B688B66FF2EF49978DC67FE0BE4383F3
